# Generated by Django 3.1.7 on 2022-01-11 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('priceMonthly', models.FloatField()),
                ('priceYearly', models.FloatField()),
                ('maxProperties', models.CharField(max_length=254)),
                ('maxImages', models.SmallIntegerField()),
                ('maxVideos', models.SmallIntegerField()),
                ('support', models.BooleanField()),
                ('smartScheduler', models.BooleanField()),
                ('propertyMonitor', models.BooleanField()),
            ],
        ),
    ]
