# Generated by Django 3.1.7 on 2022-01-11 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stripe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='priceMonthlyId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='priceYearlyId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(max_length=200)),
                ('invoice_status', models.CharField(choices=[('paid', 'paid'), ('open', 'open')], max_length=50)),
                ('subscription_status', models.CharField(choices=[('active', 'active'), ('incomplete', 'incomplete'), ('trialing', 'trialing'), ('incomplete_expired', 'incomplete_expired'), ('past_due', 'past_due'), ('canceled', 'canceled'), ('unpaid', 'unpaid')], max_length=50)),
                ('payment_intent_status', models.CharField(choices=[('succeeded', 'succeeded'), ('requiores_payment_method', 'requires_payment_method'), ('requires_action', 'requires_action')], max_length=50)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stripe.subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
