# Generated by Django 3.1.7 on 2022-01-12 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0002_auto_20220111_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='subscription_status',
            new_name='status',
        ),
    ]
