# Generated by Django 3.1.7 on 2022-01-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0005_stripesubscription_expires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripesubscription',
            old_name='expires',
            new_name='expiryDate',
        ),
    ]
