# Generated by Django 3.1.7 on 2022-01-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0006_auto_20220112_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesubscription',
            name='payment_intent_status',
            field=models.CharField(choices=[('succeeded', 'succeeded'), ('requires_payment_method', 'requires_payment_method'), ('requires_action', 'requires_action')], max_length=50, null=True),
        ),
    ]
