# Generated by Django 3.1.7 on 2022-07-19 17:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0007_auto_20220112_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscription',
            name='uuiid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
