# Generated by Django 3.1.7 on 2022-07-19 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0008_stripesubscription_uuiid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripesubscription',
            name='id',
        ),
        migrations.AlterField(
            model_name='stripesubscription',
            name='uuiid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
